name: any_text_generator
description: "talk less, generate more."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  json: ^0.20.2
  langchain_lib:
    git:
      url: https://github.com/guchengxi1994/langchain_lib
  markdown_widget: ^2.3.2+6
  riverpod: ^2.5.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  package_rename: ^1.6.0 

flutter:
  uses-material-design: true

  assets:
    - assets/settings.json
  
  fonts:
    - family: xing
      fonts:
        - asset: assets/fonts/WeiNiZhuYiLangManXingShu-2.ttf

flutter_launcher_icons:   # flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.jpeg"
